import { localId } from '@/utils/localId';
import type { ContactCard, RolodexFolder } from '@/types/card';

/**
 * Seed data for the Rolodex screen. Used as the fallback when a user has no
 * cached/synced contacts yet, so the screen always has something to render.
 */

export const MOCK_FOLDERS: RolodexFolder[] = [
  { id: 'folder-tech-fair-2026', name: 'Tech Fair 2026', isActive: true },
  { id: 'folder-career-expo', name: 'Career Expo', isActive: false },
];

const daysAgo = (n: number) => new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_CONTACTS: ContactCard[] = [
  {
    id: localId(),
    sourceCardId: null,
    fields: {
      context: 'employed',
      companyName: 'Pierce & Pierce',
      fullName: 'Patrick Bateman',
      jobTitle: 'Vice President',
      department: 'Mergers and Acquisitions',
      location: 'New York, NY',
      phone: '',
      email: '',
    },
    links: [],
    materialId: 'bone',
    templateId: 'pierceAndPierce',
    collectedAt: daysAgo(1),
    sortedAt: null,
    folderId: 'folder-tech-fair-2026',
    note: null,
    starred: true,
    source: 'nfc',
  },
  {
    id: localId(),
    sourceCardId: null,
    fields: {
      context: 'employed',
      companyName: 'Stellar Labs',
      fullName: 'Marcus Chen',
      jobTitle: 'Staff Engineer',
      department: 'Platform',
      location: 'Seattle, WA',
      phone: '',
      email: '',
    },
    links: [],
    materialId: 'carbonFiber',
    templateId: 'pierceAndPierce',
    collectedAt: daysAgo(1),
    sortedAt: null,
    folderId: 'folder-tech-fair-2026',
    note: 'Met at the Google booth, loves React Native.',
    starred: false,
    source: 'qr',
  },
  {
    id: localId(),
    sourceCardId: null,
    fields: {
      context: 'jobSeeker',
      headline: 'Full-Stack Developer',
      fullName: 'Ava Whitfield',
      targetRole: 'Full-Stack Developer',
      education: 'B.S. Computer Science, Univ. of Washington',
      location: 'Seattle, WA',
      phone: '',
      email: '',
    },
    links: [],
    materialId: 'holographicPrism',
    templateId: 'pierceAndPierce',
    collectedAt: daysAgo(2),
    sortedAt: null,
    folderId: 'folder-tech-fair-2026',
    note: null,
    starred: false,
    source: 'qr',
  },
  {
    id: localId(),
    sourceCardId: null,
    fields: {
      context: 'employed',
      companyName: 'Monarch Capital',
      fullName: 'Diane Ostrow',
      jobTitle: 'Managing Director',
      department: 'Private Equity',
      location: 'New York, NY',
      phone: '',
      email: '',
    },
    links: [],
    materialId: 'roseGoldFoil',
    templateId: 'pierceAndPierce',
    collectedAt: daysAgo(3),
    sortedAt: daysAgo(2),
    folderId: 'folder-career-expo',
    note: null,
    starred: true,
    source: 'nfc',
  },
  {
    id: localId(),
    sourceCardId: null,
    fields: {
      context: 'employed',
      companyName: 'Redline Systems',
      fullName: 'Tobias Kwan',
      jobTitle: 'Director of Engineering',
      department: 'Infrastructure',
      location: 'Austin, TX',
      phone: '',
      email: '',
    },
    links: [],
    materialId: 'brushedGunmetal',
    templateId: 'pierceAndPierce',
    collectedAt: daysAgo(5),
    sortedAt: daysAgo(4),
    folderId: 'folder-career-expo',
    note: null,
    starred: false,
    source: 'qr',
  },
  {
    id: localId(),
    sourceCardId: null,
    fields: {
      context: 'jobSeeker',
      headline: 'Creative Direction',
      fullName: 'Nadia Solheim',
      targetRole: 'Freelance',
      education: 'Portfolio linked',
      location: 'Los Angeles, CA',
      phone: '',
      email: '',
    },
    links: [],
    materialId: 'frostedGlass',
    templateId: 'pierceAndPierce',
    collectedAt: daysAgo(6),
    sortedAt: daysAgo(5),
    folderId: null,
    note: null,
    starred: false,
    source: 'qr',
  },
  {
    id: localId(),
    sourceCardId: null,
    fields: {
      context: 'employed',
      companyName: 'Halcyon Group',
      fullName: 'Whitney Faircloth',
      jobTitle: 'Head of Talent',
      department: 'Recruiting',
      location: 'Chicago, IL',
      phone: '',
      email: '',
    },
    links: [],
    materialId: 'anodizedTitanium',
    templateId: 'pierceAndPierce',
    collectedAt: daysAgo(8),
    sortedAt: daysAgo(7),
    folderId: null,
    note: null,
    starred: false,
    source: 'nfc',
  },
  {
    id: localId(),
    sourceCardId: null,
    fields: {
      context: 'jobSeeker',
      headline: 'Product Design',
      fullName: 'Yuki Tanaka',
      targetRole: 'Independent',
      education: 'B.F.A. Design, RISD',
      location: 'Portland, OR',
      phone: '',
      email: '',
    },
    links: [],
    materialId: 'rawConcrete',
    templateId: 'pierceAndPierce',
    collectedAt: daysAgo(10),
    sortedAt: daysAgo(9),
    folderId: null,
    note: null,
    starred: false,
    source: 'qr',
  },
];
